### ISSUE TITLE
Add Disrupt3rs logo to home page

### ISSUE THREAD

**Issue by djat** [CovalenceNetwork/covalence.info#2]
![disrupters_logo](https://github.com/CovalenceNetwork/covalence.info/assets/1049107/83b2fbcb-3a52-447f-a290-84b903a36d4d)

**Comment by orpheuslummis** [comment]
thank you @djat. completed with https://github.com/CovalenceNetwork/covalence.info/commit/00186b8d6d1ae2f59c5b9b148ca51ca83f255064
